### ISSUE TITLE
Announcement that next workshop is in planning

### ISSUE THREAD

**Issue by jank324** [RL4AA/RL4AA.github.io#3]
Add an announcement post that because the last workshop was so great, we are currently planning the next one for next year. I'm not sure if the theme supports pinned posts, but I think this would be the time to use one.

**Comment by cr-xu** [comment]
The `weight` parameter is exactly used to pin the post, one with smaller value gets higher, without it the posts will be ordered according to the date. 

I just removed the weights in publication posts so the announcement posts will be pinned.

**Comment by jank324** [comment]
I think we should only pin the most recent announcement. The others can fall in line with the publications, because if I want to see only announcements I can still go to the appropriate page.
